#!/usr/bin/env lua

-- luarocks: lcurses sleep
local C = require 'curses'
local LED = require 'led'
local paint = require 'paint'
local sleep = require 'sleep'

local function rectangles_of (str, fill_char)
	local rectangles = {}
	local d
	for c in str:gmatch('.') do
		if c == ':' then
			d = LED.colon:gsub('%S', fill_char)
		else
			d = LED.digit(tonumber(c), fill_char)
		end
		if d ~= nil then
			rectangles[#rectangles+1] = d
		end
	end
	return rectangles
end


C.initscr()
C.cbreak()
C.echo(false)

local scr = C.stdscr()
scr:nodelay(true)

local quit_ch = string.byte('q')

local sec0 = '60'
while true do
	local sec1 = tostring(os.time() % 60)
	if sec1 < sec0 then
		scr:clear()
		paint.rectangles(scr, 8, 6, rectangles_of(os.date('%H:%M'), '@'), 6)
		scr:move(0, 0)
		scr:refresh()
	end
	if scr:getch() == quit_ch then
		break
	end
	sec0 = sec1
	sleep(1000)
end

C.endwin()
