#!/usr/bin/env lua

-- luarocks: lcurses sleep
local C = require 'curses'
local LED = require 'led'
local paint = require 'paint'
local sleep = require 'sleep'

local function rectangles_of (str, fill_char)
	local rectangles = {}
	local d
	for c in str:gmatch('.') do
		if c == ':' then
			d = LED.colon:gsub('%S', fill_char)
		else
			d = LED.digit(tonumber(c), fill_char)
		end
		if d ~= nil then
			rectangles[#rectangles+1] = d
		end
	end
	return rectangles
end


C.initscr()
C.cbreak()
C.echo(false)

local scr = C.stdscr()
scr:nodelay(true)

local quit_ch = string.byte('q')

while true do
	scr:clear()
	local sec = tostring(os.time() % 60)
	paint.rectangles(scr, 5, 10, rectangles_of(os.date('%H:%M'), '@'), 6)
	scr:move(0, 0)
	scr:refresh()

	if scr:getch() == quit_ch then
		break
	end
	sleep(1000)
end

C.endwin()
